[project]
name = "dip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marimo>=0.14.16",
    "opencv-python>=4.12.0.88",
    "pip>=25.1.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.19.0",
]
